### ISSUE TITLE
V17\GoogleAdsClientBuilder" not found

### ISSUE THREAD

**Issue by psobhanlo** [googleads/google-ads-php#1041]
hi. i try get report for customer id.
but problem with clone and install  google-ads-php

please help

![Untitled](https://github.com/user-attachments/assets/da9ced70-f3c2-45d8-8e23-0ca0efa2f711)
![image](https://github.com/user-attachments/assets/ffdab95a-3710-49fd-be38-5ee861ffc4f7)

**Comment by psobhanlo** [comment]
after update composer json on  
 "googleads/google-ads-php": "^24.0.0",
get new error

![image](https://github.com/user-attachments/assets/c4ea81ec-dcc5-45fa-8d0b-35342df87e4b)

**Comment by fiboknacky** [comment]
We're working on this issue and I should be able to update the code within a few days. Sorry for this inconvenience.

**Comment by psobhanlo** [comment]
thanks for  answer issue,
When should I take the test?
Is there a need to do something from my side?

**Comment by fiboknacky** [comment]
The issue was fixed in PR #1043. We'll release the new version of client library later.
But you can check out the code in that pull request right now if you wish.

**Comment by psobhanlo** [comment]
I still have the error.
And I can't see anything and I have an error See this link
https://google-api.admoon.agency/show-report

I have taken your changes from the main branch.

**Comment by fiboknacky** [comment]
How did you update your project? Did you run `composer update`?

**Comment by psobhanlo** [comment]
no. i clone project and change directory to exmaple/laravel and run command ```composer install ``` to terminal

**Comment by fiboknacky** [comment]
Could you share your customer ID so I can reproduce it on my end? (I'll remove the ID once you share)
And when did you get this error? What page and what button did you click and get this error?

**Comment by psobhanlo** [comment]
can you give me your email for send google_ads_php.ini file??

Can I have a sandbox key for testing such as devloper_key or client_Id or ...?

**Comment by fiboknacky** [comment]
Please send your details to googleadsapi-support@google.com and refer to this issue.

> Can I have a sandbox key for testing such as devloper_key or client_Id or ...?
I'm not sure what you mean by the sandbox key? We do have [test accounts](https://developers.google.com/google-ads/api/docs/best-practices/test-accounts) that you can try though.

**Comment by fiboknacky** [comment]
As mentioned in [step 5 of the instructions](https://github.com/googleads/google-ads-php/tree/main/examples/LaravelSampleApp#instructions), you should copy your configured google_ads_php.ini to the same location as the README.md file of the [LaravelSampleApp](https://github.com/googleads/google-ads-php/tree/main/examples/LaravelSampleApp#instructions).

If you want to configure a refresh token programmatically, use [this method](https://github.com/googleads/google-ads-php/blob/6f37249dcb0da6485cc38e74f5e3cc00e4400a4f/src/Google/Ads/GoogleAds/Lib/OAuth2TokenBuilder.php#L108).

**Comment by psobhanlo** [comment]
i problem with laravel exmple.
please write auth code and update refresh code in laravel method
